title: Myles' Talks

description: Different technical talks I have given.

baseurl: ""
url: 'https://talks.mylesb.ca/'

author:
  name: Myles Braithwaite
  url: https://mylesb.ca/
  email: me@mylesb.ca
  twitter: mylesb

# Jekyll Assets settings
assets:
  compress:
    css: true
    js: true
  prefix: '/static'

# Build settings
permalink: /:year-:month-:day-:slug/

future: true

markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - fabfile.py
  - fabfile.pyc
